name: Windows - AnyDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/huuhieu17/freerdp/refs/heads/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Install AnyDesk
        run: cmd /c anydesk.bat

      - name: Get AnyDesk Remote ID
        run: cmd /c getAnyDeskID.bat

      - name: Time Counter
        run: python time.py
